### ISSUE TITLE
API port mismatch in k8s file

### ISSUE THREAD

**Issue by rweland** [kubemq-io/kubemq-community#18]
In several places in the `k8s.yaml` file the port listing for the API service is `8080`, however in the "CONFIG" section it lists the port as `8090`

This causes port mapping for the API port to fail, as the container is starting the API service on `8090` as requested by the config section.

Submitted a PR #17 for the change. Will need redeploy of `https://deploy.kubemq.io/community`

**Comment by kubemq** [comment]
PR Merged
