### ISSUE TITLE
Installation using kubectl

### ISSUE THREAD

**Issue by neeraj-t11** [kubemq-io/kubemq-community#22]
I tried installing Kube MQ with kubectl command mentioned : "kubectl apply -f https://deploy.kubemq.io/community".
But there is an error in installing and it says : Unable to connect to the server: x509: certificate signed by unknown authority.
Configurations:
Ubuntu VM with a minikube installation. The kubectl is configured by the minikube.

**Comment by kubemq** [comment]
Please take the yaml content from here:
https://github.com/kubemq-io/kubemq-community/blob/master/operations/k8s.yaml
