### ISSUE TITLE
ARM image?

### ISSUE THREAD

**Issue by winston0410** [kubemq-io/kubemq-community#23]
Is it possible for kubemq to provide ARM image?

**Comment by winston0410** [comment]
https://github.com/kubemq-io/kubemq-community/issues/12

I notice this issue, but I cannot find anything in the release page in Github. Should I check somewhere else?

**Comment by kubemq** [comment]
Hi,
We can compile kubemq to ARM architecture.
Can you give more info about the usecase ?
Lior,

**Comment by winston0410** [comment]
In Oracle Cloud, only ARM instance are always free. The arch will be an important factor for user to decide which MQ to use.

I think ARM is having more user as well because of MacBook, even though aarch64-darwin !== aarch64-linux

**Comment by kubemq** [comment]
Hi,
please check out the releases page:
https://github.com/kubemq-io/kubemq-community/releases/tag/v2.3.0-beta-2
You will find ARM based artifacts

**Comment by winston0410** [comment]
@kubemq Thanks for your update! I know it is a lot to ask, but I guess it will make kubemq easier to be adapted, if images of different archs are provided as well

**Comment by kubemq** [comment]
Images of what? Docker?

**Comment by winston0410** [comment]
Yes docker image. It can be acheived with `docker buildx`, and a matrix of arch(not sure if it exists for github action yet) to trigger the build flow for different arch.

**Comment by kubemq** [comment]
We will look into that
