### ISSUE TITLE
How to Delete channel type Events-Store in kubemq

### ISSUE THREAD

**Issue by kenjirawat** [kubemq-io/kubemq-community#26]
You have solution for Clear or Delete channel name type Events-Store or type other. 
Have a need to delete channel after expire date or set time for delete channel.

**Comment by kubemq** [comment]
Data is automatically deleted. The default time is 24 h of inactivity,
You can configure this to any value you Wan

**Comment by kenjirawat** [comment]
OK Thank you very much.
