### ISSUE TITLE
The kubemq cli (release v2.3.5) version return v2.3.0-beta-2

### ISSUE THREAD

**Issue by Ultchad** [kubemq-io/kubemq-community#27]
Bad version in cli 

```bash
$ curl -L 'https://github.com/kubemq-io/kubemq-community/releases/download/v2.3.5/kubemq-linux-amd64.tar.gz' | tar xzf - && \
chmod +x ./kubemq && \
./kubemq --version
# return
kubemq version v2.3.0-beta-2
```
I have tested with :
- kubemq-linux-amd64.tar.gz
- kubemq-windows-amd64.tar.gz 

I have test other release

| release version | return version |
|-----------------|----------------|
| v2.3.0-beta-1   | v2.2.13        |
| v2.3.0-beta-2   | v2.3.0-beta-1  |
| v2.3.0          | v2.3.0-beta-2  |
| v2.3.1          | v2.3.0-beta-2  |
| v2.3.2          | v2.3.0-beta-2  |
| v2.3.3          | v2.3.0-beta-2  |
| v2.3.4          | v2.3.0-beta-2  |
| v2.3.5          | v2.3.0-beta-2  |

**Comment by kubemq** [comment]
Thanks for noticing it.
I have updated the bin in the latest release
