### ISSUE TITLE
`kubemq-run` processes consume all CPU/memory

### ISSUE THREAD

**Issue by fcannizzaro** [kubemq-io/kubemq-community#30]
Hi! I'm using KubeMQ to connect some microservices, yesterday suddenly the server became inaccessible due to CPU/memory usage (usually there are ~15 `kubemq-run` processes, while in this case there were a lot of these processes that consumed every resource, below a screenshot of some of them).

![image](https://user-images.githubusercontent.com/6225939/212018916-1f020079-619c-4a5b-9980-3c8a58d8e7cd.png)

**what I did**
I deleted and recreated the cluster to fix this issue. I also made some tests to provoke it again (by sending 32k messages at the same time using parallel processes, 8k per process) and nothing happened, there was never a resource peak, so what can cause this issue?

**params**
reading the documentation I see there are some resource-related params 
```
 --resources-limits-key-CPU string			set resources limits CPU  (default "1000m")
 --resources-limits-key-memory string		set resources limits memory (default "512Mi")
 --resources-requests-key-CPU string		set resources requests CPU (default "100m")
 --resources-requests-memory string			set resources request memory (default "256Mi")
```  
but they seem to be settings per instance and do not limit the number of processes spawned by kubemq.

Any idea? Thanks

**Comment by kubemq** [comment]
Hi,
{;ease address your question on the slack channel,
