### ISSUE TITLE
Cannot start dashboard

### ISSUE THREAD

**Issue by dazraf** [kubemq-io/kubemq-community#34]
Architecture: x64
O/S: Linux 
Kubernetes environment: Minikube (latest as of date of posting this)
after following the instructions to install KubeMQ (Community), and verifying that I can send a `hello world` message, the following fails:

```bash
kubemqctl get dashboard
Current Kubernetes cluster context connection: minikube
error: the server could not find the requested resource (get kubemqdashboards.core.k8s.kubemq.io)
```

Any clues would be very much appreciated, thanks.

**Comment by kubemq** [comment]
You are mixing the Community version with the commercial version.
I suggest you contact us via the slack channel for more details.
Lior,
