### ISSUE TITLE
How to guarantee the order of messages?

### ISSUE THREAD

**Issue by shangjin92** [kubemq-io/kubemq-community#7]
If there are multi consumer within one consumer group, how to guarantee the order of message consuming? Like kafka's topic partition, each partition can be listened by each consumer, message can be hashed to special partition.

**Comment by kubemq** [comment]
The messages are ordered by default

**Comment by shangjin92** [comment]
> The messages are ordered by default

So whether the messages in queue can be consumed orderly, hen there multi consumer in one consumer group.

**Comment by kubemq** [comment]
Not sure i understand your question
